config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transactions, only: [:index, :new, :create, :destroy]
  root "transactions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  enum :transaction_type, { out_money: "saida", deposit: "entrada" }

  belongs_to :user

  validates :date, comparison: { less_than_or_equal_to: proc { Date.current } }
  validates :description, length: { maximum: 150 }
  validates :transaction_value, presence: true
  validates :transaction_type, presence: true

  validate :validate_is_there_money

  def self.total_money
    self.deposit.sum(:transaction_value) - self.out_money.sum(:transaction_value)
  end

  private

  def validate_is_there_money
    return unless user
    return if deposit?
    return if transaction_value.to_f <= user.transactions.total_money
    errors.add :transaction_value, "Without balance"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[ destroy ]

  def index
    @transactions = collection.order(date: :desc, created_at: :desc)
    @balance = collection.total_money
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = collection.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def collection
    current_user.transactions
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = collection.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:date, :description, :transaction_value, :transaction_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-slate-300">
    <main class="container mx-auto mt-28 px-5 flex"><%= yield %></main>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, class: "contents") do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(transaction.errors.count, "error", plural: 'erros') %> encontrados:</h2>
      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :transaction_type %>
    <%= form.select :transaction_type, 
      [['Entrada', 'entrada'], ['Saída', 'saida']], { }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" }
    %>
  </div>
  <div class="my-5">
    <%= form.label :date %>
    <%= form.date_field :date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :transaction_value %>
    <%= form.number_field :transaction_value, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" 
  class="flex p-6 rounded-lg shadow-lg bg-white <%= transaction.out_money? ? 'text-red-600' : 'text-green-600' %>"
>
  <span class="mr-2">
    <%= l transaction.date %>
  </span>
  <span class="mr-2 flex-grow">
    <%= number_to_currency transaction.transaction_value %>
  </span>
  <span class="mr-2">
    <%= transaction.description %>
  </span>
</div>

app/views/transactions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p
    class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block"
    id="notice"
  >
      <%= notice %>
    </p>
  <% end %>
  <div class="grid grid-cols-3 gap-3 mb-4">
    <div class="p-6 rounded-lg shadow-lg bg-white">
      <p>Saldo atual:</p>
      <p class="text-2-xl font-bold text-zinc-800">
        <%= number_to_currency @balance %>
      </p>
    </div>
    <%= link_to new_transaction_path, 
      class: "pt-7 rounded-lg py-3px-5 bg-blue-600 text-white block font-medium text-center" do %>
      <span>Nova transação</span>
    <% end %>
    <%= link_to destroy_user_session_path,
      method: :delete,
      class: "pt-4 rounded-lg py-3px-5 bg-blue-600 text-white block font-medium text-center" do %>
      <span>Logado como <%= current_user.email %></span>
      <span>Sair</span>
    <% end %>
  </div>
  <div id="transactions" class="min-w-full grid grid-cols-1 gap-3"><%= render @transactions %></div>
</div>

app/views/transactions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New transaction</h1>
  <%= render "form", transaction: @transaction %>
  <%= link_to 'Back to transactions', transactions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>